# in config/database.yml
 # this defines the database for the development environment (default environment)
development:
 adapter: sqlite3 
 database: vetsi-development

 # same but for test env
test:
 adapter: sqlite3
 database: vetsi-test

production:
 adapter: postgresql
 encoding: unicode
 pool: 5
 database: <%= ENV['DATABASE_NAME'] %>
 host: <%= ENV['DATABASE_HOST'] %>
 username: <%= ENV['DATABASE_USER'] %>
 password: <%= ENV['DATABASE_PASSWORD'] %>


