development:
 adapter: sqlite3 
 database: vetsi-development

test:
 adapter: sqlite3
 database: vetsi-test

production:
 adapter: postgresql
 pool: 5
 timeout: 5000
 database: vetsi-production
 url: <%= ENV['DATABASE_URL'] %>



