# in config/database.yml
 # this defines the database for the development environment (default environment)
development:
 # the type of database it will be
 adapter: sqlite3 
  # name of db to make
 database: vetsi-development

 # same but for test env
test:
 adapter: sqlite3
 database: vetsi-test