
version: v1.0
name: Deploy API
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: 🏁 Deploy
    task:
      secrets:
        - name: heroku-http
      jobs:
        - name: Copy to S3
          commands:
            - checkout
            - sh bin/production.sh